[package]
name = "bit_tor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "^2.4.1"
sha1_smol = {version = "1.0.0" , features = ["std"]}
reqwest = {version="^0.11.20", features=["blocking"]}
percent-encoding = "^2.3.0"
rand = "*"
regex = "1.9.6"
once_cell = "1.18.0"
